trigger:
- main

pr:
- main
 

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Scan
    displayName: Scan
    jobs:
      - job: plan
        pool:
          vmImage: ubuntu-latest
        displayName: Checkov scan
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: 'pip install checkov'
          displayName: Install checkov
        - task: Bash@3
          inputs:
            targetType: 'inline'
            workingDirectory: $(System.DefaultWorkingDirectory)            
            script: 'checkov -d . -o junitxml > Checkov-Report.xml'
          continueOnError: true
          displayName: Checkov scan
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: 'JUnit'
            searchFolder: '$(System.DefaultWorkingDirectory)'
            testResultsFiles: '**/*Checkov-Report.xml'
            mergeTestResults: false
            testRunTitle: Checkov Dev workspace scan
            failTaskOnFailedTests: false
            publishRunAttachments: true
          displayName: Publish Test Result
